spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?useSSL=true
    username: root
    password: Qj2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true
